name: iThome Data Update

on:
schedule:
- cron: '0 0 * * *' # 每天凌晨執行一次 (UTC)
workflow_dispatch: # 支援手動觸發執行

jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout Repository
uses: actions/checkout@v3
